trigger:
- Development

steps:
# 1. Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# 2. List files in the working directory (for debugging)
- script: |
    ls -R
  displayName: 'List files'

# 3. HTML syntax check using HTMLHint
- script: |
    npx htmlhint "*.html" --config .htmlhintrc
  displayName: 'HTML syntax check'

# 4. CSS syntax check using Stylelint with inline configuration
- script: |
    echo '{
      "rules": {
        "block-no-empty": true,
        "color-no-invalid-hex": true
      }
    }' > .stylelintrc.json
    npx stylelint "**/*.css"
  displayName: 'CSS Syntax Check'

# 5. PHP syntax check using PHP linter
- script: |
    find . -name "*.php" -exec php -l {} \;
  displayName: 'PHP syntax check'

# 6. Package all files into a ZIP archive
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cd $(Build.SourcesDirectory)
    zip -r $(Build.ArtifactStagingDirectory)/output.zip .
  displayName: 'Package All Files into ZIP'

# 7. Publish the ZIP file as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/output.zip'
    artifactName: 'all-files-package'
    publishLocation: 'pipeline'
  displayName: 'Publish ZIP Artifact'

# 8. Deploy the ZIP file to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'gamevaultwebapp'
    appName: 'GameVault'
    appType: 'webAppLinux'
    package: '$(Pipeline.Workspace)/all-files-package/output.zip'
  displayName: 'Deploy GameVault'
