trigger:
- Development

steps:
# 1. Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# 2. List files in the working directory (for debugging)
- script: |
    ls -R
  displayName: 'List files'

# 3. HTML syntax check using HTMLHint
- script: |
    npx htmlhint "*.html" --config .htmlhintrc
  displayName: 'HTML syntax check'

# 4. CSS syntax check using Stylelint with inline configuration
- script: |
    echo '{
      "rules": {
        "block-no-empty": true,
        "color-no-invalid-hex": true
      }
    }' > .stylelintrc.json
    npx stylelint "*.css"
  displayName: 'CSS Syntax Check'

# 5. PHP syntax check using PHP linter
- script: |
    find . -name "*.php" -exec php -l {} \;
  displayName: 'PHP syntax check'

# 6. Publish the files as an artifact (no zipping)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)' # Adjust this path as needed to include only the files you want
    artifactName: 'html-css-php-package'
    publishLocation: 'pipeline'
  displayName: 'Publish Files Artifact'
