trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Install Node.js (required for HTMLHint and Stylelint)
- task: NodeTool@0
  inputs:
    versionSpec: '14.x' # or '16.x'
  displayName: 'Install Node.js'

# 2. Install project dependencies including linting tools
- script: |
    npm install
  displayName: 'Install Dependencies'

# 3. List files in the working directory (for debugging)
- script: |
    ls -R
  displayName: 'List files'

# 4. HTML syntax check using HTMLHint
- script: |
    npx htmlhint "**/*.html" --config .htmlhintrc
  displayName: 'HTML syntax check'

# 5. CSS syntax check (if no configuration file is used, default linting rules will apply)
- script: |
    npx stylelint "**/*.css" --fix
  displayName: 'CSS syntax check'

# 6. PHP syntax check using PHP linter
- script: |
    find . -name "*.php" -exec php -l {} \;
  displayName: 'PHP syntax check'

# 7. Package HTML, CSS, and PHP files into a ZIP archive
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    find . -name "*.html" -o -name "*.php" -o -name "*.css" -exec cp {} $(Build.ArtifactStagingDirectory) \;
    cd $(Build.ArtifactStagingDirectory)
    zip -r output.zip .
  displayName: 'Package HTML, CSS, and PHP Files into ZIP'

# 8. Publish the ZIP file as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/output.zip'
    artifactName: 'html-css-php-package'
    publishLocation: 'pipeline'
  displayName: 'Publish ZIP Artifact'
