trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Lint HTML files using HTMLHint
- script: |
    npm install htmlhint
    npx htmlhint "src/**/*.html" --config .htmlhintrc
  displayName: 'Lint HTML Files'

# 2. Check PHP syntax using PHP linter
- script: |
    find src/ -name "*.php" -exec php -l {} \;
  displayName: 'Check PHP Syntax'

# 3. Package HTML and PHP files into a ZIP archive
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp -R src/* $(Build.ArtifactStagingDirectory)/
    cd $(Build.ArtifactStagingDirectory)
    zip -r output.zip .
  displayName: 'Package Files into ZIP'

# 4. Publish the ZIP file as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/output.zip'
    artifactName: 'html-php-package'
    publishLocation: 'pipeline'
  displayName: 'Publish ZIP Artifact'

